name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Compose
      run: |
        
        ls
    - name: Build the Docker image
      run: docker-compose build
    - name: Run docker image
      run: docker-compose up -d
    - name: Test api
      run: docker-compose run fastapi pytest .
